/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MeetingIdImport } from './routes/$meetingId'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MeetingIdRoute = MeetingIdImport.update({
  id: '/$meetingId',
  path: '/$meetingId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$meetingId': {
      id: '/$meetingId'
      path: '/$meetingId'
      fullPath: '/$meetingId'
      preLoaderRoute: typeof MeetingIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$meetingId': typeof MeetingIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$meetingId': typeof MeetingIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$meetingId': typeof MeetingIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$meetingId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$meetingId'
  id: '__root__' | '/' | '/$meetingId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeetingIdRoute: typeof MeetingIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeetingIdRoute: MeetingIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$meetingId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$meetingId": {
      "filePath": "$meetingId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
